import '@fortawesome/fontawesome-svg-core/styles.css'
import {config} from "@fortawesome/fontawesome-svg-core"
config.autoAddCss = false

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "@/styles/style.css";
import Navbar from '@/components/navbar';
import ReduxProvider from '@/components/redux-provider/ReduxProvider';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
        <ToastContainer />
          <ReduxProvider>
            <Navbar />
            {children}
          </ReduxProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
